version: '3.8'

services:
  db:
    image: postgres:16.6
    container_name: postgres-db
    environment:
      - POSTGRES_USER=admin         # Username for the database
      - POSTGRES_PASSWORD=secret    # Password for the database
      - POSTGRES_DB=uctaskdb      # Name of the database to create
    ports:
      - "5432:5432"                 # Expose PostgreSQL port to host machine
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data
    networks:
      - mynetwork
    restart: unless-stopped  # Restart policy for the container

volumes:
  postgres_data:
    driver: local

networks:
  mynetwork:
    driver: bridge
