services:
  db:
    image: postgres:16.6
    container_name: postgres-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=uctaskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    restart: unless-stopped

  backend:
    build:
      context: ./UcTask
      dockerfile: Dockerfile
    container_name: backend
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionString: Host=db;Port=5432;Database=uctaskdb;Username=admin;Password=secret
      DB_NAME: uctaskdb
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: secret
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mynetwork

volumes:
  postgres_data:
    driver: local

networks:
  mynetwork:
    driver: bridge
